version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
shallow_clone: true
cache: '%USERPROFILE%\.nuget\packages'
before_build:
- cmd: nuget restore ".\Extension Library\Extension Library.sln"
build:
  verbosity: minimal
before_package:
# - cmd: dir %USERPROFILE%\.nuget\packages\xunit.core\2.2.0\build\
after_build:
- cmd: >-
    dotnet pack "src\LibNETStandard10" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
    dotnet pack "src\LibNETStandard11" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
    dotnet pack "src\LibNETStandard12" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
    dotnet pack "src\LibNETStandard13" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
    dotnet pack "src\LibNETStandard14" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
    dotnet pack "src\LibNETStandard15" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
    dotnet pack "src\LibNETStandard16" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
    dotnet publish "src\ConsoleApplication" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts\ConsoleApplication
test_script:
- cmd: >-
    dotnet test "./Extension Library/ArrayExtensionTests/ArrayExtensionTests.csproj"
    dotnet test "./Extension Library/EnumerableExtensionTests/EnumerableExtensionTests.csproj"
    dotnet test "./Extension Library/StringExtensionTests/StringExtensionTests.csproj"