version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
shallow_clone: true
init:
- ps: >-
    $Env:DATETIME = Get-Date -format yyyy.MM.dd

    $Env:LABEL = "CSharpExtensionLib v" + $Env:DATETIME + "." + $Env:APPVEYOR_BUILD_NUMBER
environment:
  #Do not report to MS
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
cache: '%USERPROFILE%\.nuget\packages'
before_build:
- cmd: nuget restore ".\Extension Library\Extension Library.sln"
# build:
#   verbosity: minimal
build_script:
- cmd: dotnet build ".\Extension Library\Extension Library.sln" --no-dependencies --version-suffix %LABEL%
before_package:
# - cmd: dir %USERPROFILE%\.nuget\packages\xunit.core\2.2.0\build\
after_build:
- cmd: >-
    dotnet pack ".\Extension Library\Extensions\Extensions.csproj" --no-build --version-suffix %LABEL% -o artifacts
test_script:
- cmd: >-
    dotnet test ".\Extension Library\ArrayExtensionTests\ArrayExtensionTests.csproj"
    dotnet test ".\Extension Library\EnumerableExtensionTests\EnumerableExtensionTests.csproj"
    dotnet test ".\Extension Library\StringExtensionTests\StringExtensionTests.csproj"
artifacts:
# - path: artifacts\**\*.*